name: Deploy to Cloud Run

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Setup Node.js environment  
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'

    - name: Deploy to Cloud Run
      uses: 'google-github-actions/deploy-cloudrun@v1'
      with:
        service: '${ env.SERVICE }'
        region: '${ env.REGION }'  # Fix typo: RECION → REGION
        source: '/'

    - name: Show Cloud Run URL
      run: |
        echo "Service deployed to: ${{ steps.deploy.outputs.url }}"
        gcloud services enable \
  run.googleapis.com \
  artifactregistry.googleapis.com \
  cloudbuild.googleapis.com
